/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pruebaproyecto2;

/**
 *
 * @author Andrés
 */
public class WelcomeMenu extends javax.swing.JFrame {

    private static Master master;
    
    /**
    * Descripción: Este constructor crea la ventana WelcomeMenu y almacena los datos del objeto master con el que fue creada.
    * @author Andrés
    * @version 23/11/2023
    * Nombres y tipos de parámetros: Un objeto tipo Master llamado master que almacena la información de la base de datos.
    */
    public WelcomeMenu(Master master) {
        initComponents();
        WelcomeMenu.setMaster(master);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    public static void setMaster(Master master) {
        WelcomeMenu.master = master;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        welcomeText2 = new javax.swing.JLabel();
        printerMenu = new javax.swing.JButton();
        usersMenu = new javax.swing.JButton();
        welcomeText = new javax.swing.JLabel();
        Wallpaper = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomeText2.setBackground(new java.awt.Color(255, 255, 255));
        welcomeText2.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        welcomeText2.setForeground(new java.awt.Color(0, 0, 0));
        welcomeText2.setText("de impresiones");
        jPanel1.add(welcomeText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 210, 30));

        printerMenu.setText("Menú de Impresora");
        printerMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printerMenuActionPerformed(evt);
            }
        });
        jPanel1.add(printerMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 160, 70));

        usersMenu.setText("Menú de Usuarios");
        usersMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersMenuActionPerformed(evt);
            }
        });
        jPanel1.add(usersMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 160, 70));

        welcomeText.setBackground(new java.awt.Color(255, 255, 255));
        welcomeText.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        welcomeText.setForeground(new java.awt.Color(0, 0, 0));
        welcomeText.setText("Bienvenid@ al sistema");
        jPanel1.add(welcomeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 290, 40));

        Wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Welcome.jpg"))); // NOI18N
        jPanel1.add(Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 380));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void printerMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printerMenuActionPerformed
        this.setVisible(false);
        new PrinterMenu(master);
    }//GEN-LAST:event_printerMenuActionPerformed

    private void usersMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersMenuActionPerformed
        this.setVisible(false);
        new UsersMenu(master);
    }//GEN-LAST:event_usersMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomeMenu(master).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Wallpaper;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton printerMenu;
    private javax.swing.JButton usersMenu;
    private javax.swing.JLabel welcomeText;
    private javax.swing.JLabel welcomeText2;
    // End of variables declaration//GEN-END:variables
}
